### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by kodibrain** [Killerameise/homebridge-rc433-motion-sensor#3]
Hi,
habe ein Problem mit deinem plugin, weiß nicht woran es liegt. Sobald der 433MHz code empfangen wird crasht die homebridge.
####
**_{"code": 1361, "pulseLength": 310}{"code": 1361, "pulseLength": 310}{"code": 1361, "pulseLength": 311}
                                  ^
SyntaxError: Unexpected token { in JSON at position 34
    at JSON.parse (<anonymous>)
    at Sniffer.onData (/usr/local/lib/node_modules/homebridge-rc433-motion-sensor/node_modules/rpi-433/Sniffer.js:61:26)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-rc433-motion-sensor/node_modules/underscore/underscore.js:841:23)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)_**
####
ich nutze nebenbei das plugin homebridge-rcswitch-gpiomem zum schalten meiner 433MHz Hardware, hängt es damit vielleicht zudammen?

**Comment by Killerameise** [comment]
Hi, 

das Problem liegt am rpi-433 Projekt. Wenn in extrem kurzen Abstand zwei Signale ankommen, kommt es zu diesem Fehler. Ich hatte noch keine Zeit beim eigentlich Projekt ein Issue zu erstellen.
Ich habe aber einen Workaround:
Ersetze folgende Methode in der Sniffer.js Klasse.  Diese findet sich unter den node_modules in rpi-433. Bei dir ist das hier: /usr/local/lib/node_modules/homebridge-rc433-motion-sensor/node_modules/rpi-433/Sniffer.js. Es handelt sich um Zeile 59 bis 63:

```javascript
Sniffer.prototype.onData = function (buffer) {
  
  this.emit('data', JSON.parse(buffer));
  
};
```

Ersetze sie durch:

```javascript
Sniffer.prototype.onData = function (buffer) {
buffer = buffer.toString('utf8');
  if(buffer.includes("}{")){
        buffer = buffer.replace("}{","}${");
        var bufferArray = buffer.split("$");
        for (str in bufferArray) {
                this.emit('data', JSON.parse(str));
        }
  }else{
        this.emit('data', JSON.parse(buffer));
  }
};
```

Anschließend sollte der Fehler nicht mehr auftreten.

**Comment by kodibrain** [comment]
Hi,
super vielen Dank, hat funktioniert.
